[environments]
  [environments.development]
    name = "gowebsockettest"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = true
    dockerfile = "Dockerfile"
    chart = ""
    custom-tags = ["latest"]

  [environments.production]
    name = "gowebsockettest"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
    registry = "docker.io/eyjohn"
    custom-tags = ["latest"]
